// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: proto/jam.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateJailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Persist bool   `protobuf:"varint,1,opt,name=persist,proto3" json:"persist,omitempty"`
	Host    *Host  `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Path    string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *CreateJailRequest) Reset() {
	*x = CreateJailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_jam_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateJailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJailRequest) ProtoMessage() {}

func (x *CreateJailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jam_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJailRequest.ProtoReflect.Descriptor instead.
func (*CreateJailRequest) Descriptor() ([]byte, []int) {
	return file_proto_jam_proto_rawDescGZIP(), []int{0}
}

func (x *CreateJailRequest) GetPersist() bool {
	if x != nil {
		return x.Persist
	}
	return false
}

func (x *CreateJailRequest) GetHost() *Host {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *CreateJailRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CreateJailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output string `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *CreateJailResponse) Reset() {
	*x = CreateJailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_jam_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateJailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJailResponse) ProtoMessage() {}

func (x *CreateJailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jam_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJailResponse.ProtoReflect.Descriptor instead.
func (*CreateJailResponse) Descriptor() ([]byte, []int) {
	return file_proto_jam_proto_rawDescGZIP(), []int{1}
}

func (x *CreateJailResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type JailOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Persist bool   `protobuf:"varint,2,opt,name=persist,proto3" json:"persist,omitempty"`
	Path    string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *JailOptions) Reset() {
	*x = JailOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_jam_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JailOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JailOptions) ProtoMessage() {}

func (x *JailOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jam_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JailOptions.ProtoReflect.Descriptor instead.
func (*JailOptions) Descriptor() ([]byte, []int) {
	return file_proto_jam_proto_rawDescGZIP(), []int{2}
}

func (x *JailOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JailOptions) GetPersist() bool {
	if x != nil {
		return x.Persist
	}
	return false
}

func (x *JailOptions) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Host struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host     string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	HostName string `protobuf:"bytes,2,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
}

func (x *Host) Reset() {
	*x = Host{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_jam_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jam_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_proto_jam_proto_rawDescGZIP(), []int{3}
}

func (x *Host) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Host) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

type Mount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Devfs   bool `protobuf:"varint,1,opt,name=devfs,proto3" json:"devfs,omitempty"`
	NoDevfs bool `protobuf:"varint,2,opt,name=no_devfs,json=noDevfs,proto3" json:"no_devfs,omitempty"`
}

func (x *Mount) Reset() {
	*x = Mount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_jam_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mount) ProtoMessage() {}

func (x *Mount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jam_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mount.ProtoReflect.Descriptor instead.
func (*Mount) Descriptor() ([]byte, []int) {
	return file_proto_jam_proto_rawDescGZIP(), []int{4}
}

func (x *Mount) GetDevfs() bool {
	if x != nil {
		return x.Devfs
	}
	return false
}

func (x *Mount) GetNoDevfs() bool {
	if x != nil {
		return x.NoDevfs
	}
	return false
}

type ListJailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListJailsResponse) Reset() {
	*x = ListJailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_jam_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListJailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJailsResponse) ProtoMessage() {}

func (x *ListJailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jam_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJailsResponse.ProtoReflect.Descriptor instead.
func (*ListJailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_jam_proto_rawDescGZIP(), []int{5}
}

type ListJailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListJailsRequest) Reset() {
	*x = ListJailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_jam_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListJailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJailsRequest) ProtoMessage() {}

func (x *ListJailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jam_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJailsRequest.ProtoReflect.Descriptor instead.
func (*ListJailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_jam_proto_rawDescGZIP(), []int{6}
}

var File_proto_jam_proto protoreflect.FileDescriptor

var file_proto_jam_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6a, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x5c, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05,
	0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22,
	0x2c, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x4f, 0x0a,
	0x0b, 0x4a, 0x61, 0x69, 0x6c, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x37,
	0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x6f,
	0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68,
	0x6f, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x38, 0x0a, 0x05, 0x4d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x76, 0x66, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x64, 0x65, 0x76, 0x66, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x5f, 0x64, 0x65, 0x76,
	0x66, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x6e, 0x6f, 0x44, 0x65, 0x76, 0x66,
	0x73, 0x22, 0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x4a, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4a, 0x61,
	0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x32, 0x74, 0x0a, 0x03, 0x4a, 0x61,
	0x6d, 0x12, 0x37, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x61, 0x69, 0x6c, 0x12,
	0x12, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x09, 0x4c, 0x69,
	0x73, 0x74, 0x4a, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x11, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4a, 0x61,
	0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x4a, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65,
	0x64, 0x73, 0x6f, 0x6e, 0x6d, 0x69, 0x63, 0x68, 0x61, 0x71, 0x75, 0x65, 0x2f, 0x6a, 0x61, 0x6d,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_jam_proto_rawDescOnce sync.Once
	file_proto_jam_proto_rawDescData = file_proto_jam_proto_rawDesc
)

func file_proto_jam_proto_rawDescGZIP() []byte {
	file_proto_jam_proto_rawDescOnce.Do(func() {
		file_proto_jam_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_jam_proto_rawDescData)
	})
	return file_proto_jam_proto_rawDescData
}

var file_proto_jam_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_jam_proto_goTypes = []interface{}{
	(*CreateJailRequest)(nil),  // 0: CreateJailRequest
	(*CreateJailResponse)(nil), // 1: CreateJailResponse
	(*JailOptions)(nil),        // 2: JailOptions
	(*Host)(nil),               // 3: Host
	(*Mount)(nil),              // 4: Mount
	(*ListJailsResponse)(nil),  // 5: ListJailsResponse
	(*ListJailsRequest)(nil),   // 6: ListJailsRequest
}
var file_proto_jam_proto_depIdxs = []int32{
	3, // 0: CreateJailRequest.host:type_name -> Host
	0, // 1: Jam.CreateJail:input_type -> CreateJailRequest
	6, // 2: Jam.ListJails:input_type -> ListJailsRequest
	1, // 3: Jam.CreateJail:output_type -> CreateJailResponse
	5, // 4: Jam.ListJails:output_type -> ListJailsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_jam_proto_init() }
func file_proto_jam_proto_init() {
	if File_proto_jam_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_jam_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateJailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_jam_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateJailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_jam_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JailOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_jam_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Host); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_jam_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_jam_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListJailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_jam_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListJailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_jam_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_jam_proto_goTypes,
		DependencyIndexes: file_proto_jam_proto_depIdxs,
		MessageInfos:      file_proto_jam_proto_msgTypes,
	}.Build()
	File_proto_jam_proto = out.File
	file_proto_jam_proto_rawDesc = nil
	file_proto_jam_proto_goTypes = nil
	file_proto_jam_proto_depIdxs = nil
}
